### ISSUE TITLE
Modrinth versions issue

### ISSUE THREAD

**Issue by mpustovoi** [ITsMrToad/GpuTape#2]
When I install this mod for Forge 1.20.1 it looks fine
![image](https://github.com/user-attachments/assets/c4b94933-ff6f-44da-9305-e46e4a96a556)

However, actually I get the NeoForge version somehow
![image](https://github.com/user-attachments/assets/43fc7aed-4aa5-4acb-8e69-c5bf6813c7f6)

After that the `Update` button endlessly downloads this file for NeoForge.

**Comment by mpustovoi** [comment]
Or maybe I'm getting the right file, but it's not indexed correctly in Modrinth.

**Comment by ITsMrToad** [comment]
> Or maybe I'm getting the right file, but it's not indexed correctly in Modrinth.

Yes, the file is correct. The presented problem is a Modrinth app problem

**Comment by mpustovoi** [comment]
I have had similar problems from time to time with the Modrinth App. Each time they were solved by a fictitious new mod release for that version.
I don't think this issue will be considered separately by Modrinth. Or, maybe, such an issue is already known and has been reported.
