### ISSUE TITLE
question regarding fix GPU memory leak

### ISSUE THREAD

**Issue by mateus3c** [ITsMrToad/GpuTape#3]
So, I was curious to know how this compares to [fix GPU memory leak](https://www.curseforge.com/minecraft/mc-mods/fix-gpu-memory-leak). Does it already include their fixes?

**Comment by ITsMrToad** [comment]
'fix GPU memory leak' is identical to 'VideoTape' (At least the version for 1.20.1), and GPUTape is an improved version of 'VideoTape', i.e. all advantages over 'VideoTape' will apply to 'fix GPU memory leak' as well.

**Comment by VaporeonScripts** [comment]
so does this mean that this mod should be used instead of fix GPU memory leak?
